name: Set up test project
description: Sets up the test project fixture in CI for smoke tests and CLI checks

runs:
  using: node24
  main: 'setUpTestProject.mjs'

inputs:
  canary:
    description: Upgrade the project to canary?
    default: 'false'

outputs:
  test-project-path:
    description: Path to the test project
