// This file was generated by CedarJS
import * as Cell from './AuthorCell.js'
import type { CellProps } from '@cedarjs/web'
import type { FindAuthorQuery, FindAuthorQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './AuthorCell.js'

type CellInputs = CellProps<SuccessType, FindAuthorQuery, typeof Cell, FindAuthorQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
