// This file was generated by CedarJS
import * as Cell from './BlogPostCell.js'
import type { CellProps } from '@cedarjs/web'
import type { FindBlogPostQuery, FindBlogPostQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './BlogPostCell.js'

type CellInputs = CellProps<SuccessType, FindBlogPostQuery, typeof Cell, FindBlogPostQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
