// This file was generated by CedarJS
import * as Cell from './BlogPostsCell.js'
import type { CellProps } from '@cedarjs/web'
import type { BlogPostsQuery, BlogPostsQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './BlogPostsCell.js'

type CellInputs = CellProps<SuccessType, BlogPostsQuery, typeof Cell, BlogPostsQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
