// This file was generated by CedarJS
import * as Cell from './WaterfallBlogPostCell.js'
import type { CellProps } from '@cedarjs/web'
import type { FindWaterfallBlogPostQuery, FindWaterfallBlogPostQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './WaterfallBlogPostCell.js'

type CellInputs = CellProps<SuccessType, FindWaterfallBlogPostQuery, typeof Cell, FindWaterfallBlogPostQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
