// This file was generated by CedarJS
import * as Cell from './TodoListCell.js'
import type { CellProps } from '@cedarjs/web'
import type { TodoListCell_GetTodos, TodoListCell_GetTodosVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './TodoListCell.js'

type CellInputs = CellProps<SuccessType, TodoListCell_GetTodos, typeof Cell, TodoListCell_GetTodosVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
