// This file was generated by CedarJS
import * as Cell from './ContactCell.js'
import type { CellProps } from '@cedarjs/web'
import type { FindContactById, FindContactByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ContactCell.js'

type CellInputs = CellProps<SuccessType, FindContactById, typeof Cell, FindContactByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
