// This file was generated by CedarJS
import * as Cell from './EditPostCell.js'
import type { CellProps } from '@cedarjs/web'
import type { EditPostById, EditPostByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditPostCell.js'

type CellInputs = CellProps<SuccessType, EditPostById, typeof Cell, EditPostByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
