// This file was generated by CedarJS
import * as Cell from './EditContactCell.js'
import type { CellProps } from '@cedarjs/web'
import type { EditContactById, EditContactByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditContactCell.js'

type CellInputs = CellProps<SuccessType, EditContactById, typeof Cell, EditContactByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
