name: Set up RSA test project from fixture
description: Sets up an RSA project for smoke-tests

runs:
  using: node24
  main: 'setUpRsaProjectGitHub.mts'

outputs:
  kitchen-sink-project-path:
    description: Path to the test project
