// This file was generated by CedarJS
import * as Cell from './NumTodosTwoCell.js'
import type { CellProps } from '@cedarjs/web'
import type { NumTodosCell_GetCount, NumTodosCell_GetCountVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './NumTodosTwoCell.js'

type CellInputs = CellProps<SuccessType, NumTodosCell_GetCount, typeof Cell, NumTodosCell_GetCountVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
