// This file was generated by CedarJS
import { RouteParams, QueryParams } from '@cedarjs/router'

declare module '@cedarjs/router' {
  interface AvailableRoutes {
    // Only "<Route />" components with a "name" and "path" prop will be populated here.
    home: (params?: RouteParams<"/"> & QueryParams) => "/"
    typescriptPage: (params?: RouteParams<"/typescript"> & QueryParams) => "/typescript"
    someOtherPage: (params?: RouteParams<"/somewhereElse"> & QueryParams) => "/somewhereElse"
    fooPage: (params?: RouteParams<"/foo"> & QueryParams) => "/foo"
    barPage: (params?: RouteParams<"/bar"> & QueryParams) => "/bar"
    privatePage: (params?: RouteParams<"/private-page"> & QueryParams) => "/private-page"
    privatePageAdmin: (params?: RouteParams<"/private-page-admin"> & QueryParams) => "/private-page-admin"
    privatePageAdminSuper: (params?: RouteParams<"/private-page-admin-super"> & QueryParams) => "/private-page-admin-super"
  }

  export function useRoutePaths(): Record<keyof AvailableRoutes, string>
  export function useRoutePath(routeName: keyof AvailableRoutes): string

  /** Gets the name of the current route (as defined in your Routes file) */
  export function useRouteName(): keyof AvailableRoutes | undefined
}

//# sourceMappingURL=web-routerRoutes.d.ts.map
