import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { parseArgs as nodeUtilParseArgs } from 'node:util'

import ansis from 'ansis'
import { $, cd, glob, path, within } from 'zx'

export const TARBALL_DEST_DIRNAME = 'tarballs'

export const FRAMEWORK_PATH = fileURLToPath(
  new URL('../../../', import.meta.url),
)

export const IGNORE_EXTENSIONS = ['.DS_Store']

/**
 * Add to this array of strings, RegExps, or functions (whichever makes the most sense)
 * to ignore files that we don't want triggering package rebuilds.
 */
export const IGNORED = [
  /node_modules/,

  /packages\/codemods/,
  /packages\/create-cedar-app/,

  /dist/,

  /__fixtures__/,
  /__mocks__/,
  /__tests__/,
  /\.test\./,
  /jest.config.{js,ts}/,

  /README.md/,

  // esbuild emits meta.json files that we sometimes suffix.
  /meta.(\w*\.?)json/,

  /tsconfig.tsbuildinfo/,
  /tsconfig.build.tsbuildinfo/,
  /tsconfig.cjs.tsbuildinfo/,

  // The tarballs generated by `yarn build:pack`
  /cedar-.*\.tgz$/,

  (filePath: string) => IGNORE_EXTENSIONS.some((ext) => filePath.endsWith(ext)),
]

export interface Options {
  projectPath: string
  watch: boolean
  verbose: boolean
}

export async function getOptions(): Promise<Options> {
  const { positionals, values } = nodeUtilParseArgs({
    allowPositionals: true,
    options: {
      verbose: {
        type: 'boolean',
        default: false,
        short: 'v',
      },
      watch: {
        type: 'boolean',
        default: false,
        short: 'w',
      },
    },
  })
  const [projectPath] = positionals

  const options: Options = {
    projectPath:
      projectPath ?? process.env.CEDAR_CWD ?? process.env.RWJS_CWD ?? '',
    watch: values.watch ?? false,
    verbose: values.verbose ?? false,
  }

  if (!options.projectPath) {
    throw new Error(
      [
        'Error: You have to provide the path to a Cedar project as',
        '',
        '  1. the first positional argument',
        '',
        ansis.gray('  yarn project:tarsync /path/to/cedar/project'),
        '',
        '  2. the `CEDAR_CWD` env var',
        '',
        ansis.gray('  CEDAR_CWD=/path/to/cedar/project yarn project:tarsync'),
      ].join('\n'),
    )
  }

  // This makes `projectPath` an absolute path and throws if it doesn't exist.
  options.projectPath = await fs.promises.realpath(options.projectPath)

  return options
}

export async function buildTarballs() {
  await $`yarn nx run-many -t build:pack --exclude create-cedar-app`
}

export async function copyTarballs(projectPath: string) {
  const tarballDest = path.join(projectPath, TARBALL_DEST_DIRNAME)
  await fs.promises.mkdir(tarballDest, { recursive: true })

  const tarballs = await glob(['./packages/**/*.tgz'])

  await Promise.all(
    tarballs.map(async (tarball) => {
      const dest = path.join(tarballDest, path.basename(tarball))
      await fs.promises.copyFile(tarball, dest)
    }),
  )
}

export type PackageManager = 'yarn' | 'pnpm'

export async function detectPackageManager(projectPath: string) {
  const yarnLockExists = fs.existsSync(path.join(projectPath, 'yarn.lock'))
  const pnpmLockExists = fs.existsSync(path.join(projectPath, 'pnpm-lock.yaml'))

  if (pnpmLockExists && !yarnLockExists) {
    return 'pnpm'
  }

  return 'yarn'
}

export async function updateResolutions(projectPath: string) {
  const packageManager = await detectPackageManager(projectPath)

  // Always use yarn to list Cedar framework packages. The monorepo is a yarn
  // workspace regardless of what package manager the user project uses.
  const rawList = (await $`yarn workspaces list --json`).stdout.trim()

  const workspaces = rawList
    .split('\n')
    .map((line) => JSON.parse(line))
    // Filter out the root workspace.
    .filter(({ name }) => name)

  const resolutions = workspaces.reduce<Record<string, string>>(
    (acc, { name }) => {
      // Turn a Cedar package name like `@cedarjs/project-config` into `cedarjs-project-config.tgz`.
      const tgzName = `${name.replace('@', '').replaceAll('/', '-')}.tgz`

      return {
        ...acc,
        [name]: `${projectPath}/${TARBALL_DEST_DIRNAME}/${tgzName}`,
      }
    },
    {},
  )

  const projectPackageJsonPath = path.join(projectPath, 'package.json')
  const projectPackageJson = JSON.parse(
    await fs.promises.readFile(projectPackageJsonPath, 'utf-8'),
  )

  const reactResolutions = await getReactResolutions()

  let updatedPackageJson: Record<string, unknown>

  if (packageManager === 'pnpm') {
    const allOverrides = {
      ...resolutions,
      ...reactResolutions,
      graphql: '16.13.2',
    }

    const pnpmWorkspacePath = path.join(projectPath, 'pnpm-workspace.yaml')
    let workspaceContent = await fs.promises.readFile(
      pnpmWorkspacePath,
      'utf-8',
    )

    const overrideLines = Object.entries(allOverrides)
      .map(([key, value]) => `  '${key}': '${value}'`)
      .join('\n')

    const overridesMatch = workspaceContent.match(/^(overrides:.*)$/m)
    if (overridesMatch) {
      const overrideStart = overridesMatch.index! + overridesMatch[0].length
      const afterHeader = workspaceContent.slice(overrideStart)
      const existingLines = afterHeader.split('\n')
      let lastOverrideLine = 0
      const overrideEnd = (() => {
        for (let i = 1; i < existingLines.length; i++) {
          if (/^\S/.test(existingLines[i]) && existingLines[i].trim()) {
            return i
          }
          if (/^\s+'.+':/.test(existingLines[i])) {
            lastOverrideLine = i
          }
        }
        return lastOverrideLine + 1
      })()

      const existingBlock = existingLines.slice(1, overrideEnd).join('\n')
      const existingKeys = new Set(
        existingBlock
          .split('\n')
          .map((l) => l.match(/^\s+'([^']+)':/)?.[1])
          .filter(Boolean),
      )

      const newLines = Object.entries(allOverrides)
        .filter(([key]) => !existingKeys.has(key))
        .map(([key, value]) => `  '${key}': '${value}'`)
        .join('\n')

      if (newLines) {
        const insertAt =
          overrideStart +
          existingLines.slice(0, lastOverrideLine + 1).join('\n').length

        workspaceContent =
          workspaceContent.slice(0, insertAt + 1) +
          '\n' +
          newLines +
          workspaceContent.slice(insertAt + 1)
      }
    } else {
      workspaceContent += '\noverrides:\n' + overrideLines + '\n'
    }

    await fs.promises.writeFile(pnpmWorkspacePath, workspaceContent)

    // Add direct dependencies for workspace packages that are normally
    // hoisted by yarn but need to be explicit for pnpm's strict isolation.
    const webPkgPath = path.join(projectPath, 'web/package.json')
    const webPkg = JSON.parse(await fs.promises.readFile(webPkgPath, 'utf-8'))
    webPkg.dependencies['graphql-tag'] = '2.12.6'
    webPkg.dependencies['react-hook-form'] = '7.74.0'
    await fs.promises.writeFile(webPkgPath, JSON.stringify(webPkg, null, 2))

    const apiPkgPath = path.join(projectPath, 'api/package.json')
    const apiPkg = JSON.parse(await fs.promises.readFile(apiPkgPath, 'utf-8'))
    apiPkg.dependencies['@prisma/client'] = '7.8.0'
    await fs.promises.writeFile(apiPkgPath, JSON.stringify(apiPkg, null, 2))

    updatedPackageJson = { ...projectPackageJson }
    delete updatedPackageJson.pnpm
  } else {
    updatedPackageJson = {
      ...projectPackageJson,
      resolutions: {
        ...projectPackageJson.resolutions,
        ...resolutions,
        ...reactResolutions,
      },
    }
  }

  await fs.promises.writeFile(
    projectPackageJsonPath,
    JSON.stringify(updatedPackageJson, null, 2),
  )
}

export async function getReactResolutions() {
  const packageConfig = JSON.parse(
    await fs.promises.readFile(
      path.join(FRAMEWORK_PATH, 'packages/web/package.json'),
      'utf-8',
    ),
  )

  const react = packageConfig.peerDependencies.react
  const reactDom = packageConfig.peerDependencies['react-dom']

  if (!react || !reactDom) {
    throw new Error(
      "Couldn't find react or react-dom in @cedarjs/web's peerDependencies",
    )
  }

  return {
    react,
    'react-dom': reactDom,
  }
}

export async function pmInstall(projectPath: string, verbose = false) {
  const packageManager = await detectPackageManager(projectPath)

  if (verbose) {
    console.log(
      `[tarsync] Running '${packageManager} install' in ${projectPath}`,
    )
  }
  const start = Date.now()

  await within(async () => {
    cd(projectPath)
    await $`${packageManager} install`
  })

  if (verbose) {
    const elapsed = Date.now() - start
    console.log(
      `[tarsync] '${packageManager} install' completed in ${elapsed}ms`,
    )
  }

  // Verify that the install actually produced a lockfile. On Windows the
  // install process can crash (e.g. V8 Maglev JIT bug, exit code 0xC0000409)
  // without zx detecting a non-zero exit code. If the lockfile is still
  // missing after install, fail loudly here rather than silently producing a
  // broken project that fails at a later, less obvious step.
  const lockfileName =
    packageManager === 'pnpm' ? 'pnpm-lock.yaml' : 'yarn.lock'
  const lockfilePath = path.join(projectPath, lockfileName)
  if (!fs.existsSync(lockfilePath)) {
    throw new Error(
      `[tarsync] '${packageManager} install' completed but ${lockfileName} was not created in ${projectPath}. ` +
        `The install process likely crashed silently (e.g. V8 Maglev JIT bug on Windows). ` +
        `Check the install output above for clues.`,
    )
  }

  if (verbose) {
    console.log(`[tarsync] ${lockfileName} exists after install — OK`)
  }
}
