import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { parseArgs as nodeUtilParseArgs } from 'node:util'

import ansis from 'ansis'
import { $, cd, glob, path, within } from 'zx'

export const TARBALL_DEST_DIRNAME = 'tarballs'

export const FRAMEWORK_PATH = fileURLToPath(
  new URL('../../../', import.meta.url),
)

export const IGNORE_EXTENSIONS = ['.DS_Store']

/**
 * Add to this array of strings, RegExps, or functions (whichever makes the most sense)
 * to ignore files that we don't want triggering package rebuilds.
 */
export const IGNORED = [
  /node_modules/,

  /packages\/codemods/,
  /packages\/create-cedar-app/,

  /dist/,

  /__fixtures__/,
  /__mocks__/,
  /__tests__/,
  /\.test\./,
  /jest.config.{js,ts}/,

  /README.md/,

  // esbuild emits meta.json files that we sometimes suffix.
  /meta.(\w*\.?)json/,

  /tsconfig.tsbuildinfo/,
  /tsconfig.build.tsbuildinfo/,
  /tsconfig.cjs.tsbuildinfo/,

  // The tarballs generated by `yarn build:pack`
  /cedar-.*\.tgz$/,

  (filePath: string) => IGNORE_EXTENSIONS.some((ext) => filePath.endsWith(ext)),
]

export interface Options {
  projectPath: string
  watch: boolean
  verbose: boolean
}

export async function getOptions(): Promise<Options> {
  const { positionals, values } = nodeUtilParseArgs({
    allowPositionals: true,
    options: {
      verbose: {
        type: 'boolean',
        default: false,
        short: 'v',
      },
      watch: {
        type: 'boolean',
        default: false,
        short: 'w',
      },
    },
  })
  const [projectPath] = positionals

  const options: Options = {
    projectPath:
      projectPath ?? process.env.CEDAR_CWD ?? process.env.RWJS_CWD ?? '',
    watch: values.watch ?? false,
    verbose: values.verbose ?? false,
  }

  if (!options.projectPath) {
    throw new Error(
      [
        'Error: You have to provide the path to a Cedar project as',
        '',
        '  1. the first positional argument',
        '',
        ansis.gray('  yarn project:tarsync /path/to/cedar/project'),
        '',
        '  2. the `CEDAR_CWD` env var',
        '',
        ansis.gray('  CEDAR_CWD=/path/to/cedar/project yarn project:tarsync'),
      ].join('\n'),
    )
  }

  // This makes `projectPath` an absolute path and throws if it doesn't exist.
  options.projectPath = await fs.promises.realpath(options.projectPath)

  return options
}

export async function buildTarballs() {
  await $`yarn nx run-many -t build:pack --exclude create-cedar-app`
}

export async function copyTarballs(projectPath: string) {
  const tarballDest = path.join(projectPath, TARBALL_DEST_DIRNAME)
  await fs.promises.mkdir(tarballDest, { recursive: true })

  const tarballs = await glob(['./packages/**/*.tgz'])

  await Promise.all(
    tarballs.map(async (tarball) => {
      const dest = path.join(tarballDest, path.basename(tarball))
      await fs.promises.copyFile(tarball, dest)
    }),
  )
}

export type PackageManager = 'yarn' | 'npm' | 'pnpm'

function isPackageManager(value: unknown): value is PackageManager {
  return value === 'yarn' || value === 'npm' || value === 'pnpm'
}

/**
 * Work out which package manager the *target project* uses.
 *
 * Deliberately reads the project rather than the ambient environment.
 * `npm_config_user_agent` is no help here: tarsync is normally reached through
 * `cfw`, which runs it as a script of the framework repo — a yarn workspace —
 * so that variable always says "yarn" no matter what the target project uses.
 *
 * Lockfiles alone aren't enough either, because a lockfile is an *output* of
 * the first install. A project being set up for pnpm or npm won't have one yet,
 * so we also accept the markers that exist before install: pnpm's workspace
 * file, and the `packageManager` field.
 */
export async function detectPackageManager(
  projectPath: string,
): Promise<PackageManager> {
  const exists = (file: string) => fs.existsSync(path.join(projectPath, file))

  // An explicit `packageManager` field wins — it's what corepack reads, so
  // it's the closest thing to the project stating its own intent
  try {
    const packageJson: unknown = JSON.parse(
      await fs.promises.readFile(
        path.join(projectPath, 'package.json'),
        'utf-8',
      ),
    )

    if (
      packageJson &&
      typeof packageJson === 'object' &&
      'packageManager' in packageJson &&
      typeof packageJson.packageManager === 'string'
    ) {
      const name = packageJson.packageManager.split('@')[0]

      if (isPackageManager(name)) {
        return name
      }
    }
  } catch {
    // No package.json, or it isn't readable — fall through to the file checks
  }

  const yarnLockExists = exists('yarn.lock')

  if (
    (exists('pnpm-lock.yaml') || exists('pnpm-workspace.yaml')) &&
    !yarnLockExists
  ) {
    return 'pnpm'
  }

  if (exists('package-lock.json') && !yarnLockExists) {
    return 'npm'
  }

  return 'yarn'
}

/**
 * Paths to every workspace's package.json, taken from the root manifest's
 * `workspaces` field.
 *
 * Only the trailing `*` / `**` form is expanded — that covers what Cedar
 * projects use (`["api", "web", "packages/*"]`) without pulling in a glob
 * dependency. Anything fancier is left as a literal directory, which simply
 * won't exist and gets filtered out.
 */
async function findWorkspaceManifests(
  projectPath: string,
  rootPackageJson: Record<string, any>,
): Promise<string[]> {
  const workspaces = rootPackageJson.workspaces
  const patterns: string[] = Array.isArray(workspaces)
    ? workspaces
    : (workspaces?.packages ?? [])

  const directories: string[] = []

  for (const pattern of patterns) {
    const wildcard = pattern.match(/^(.*)\/\*{1,2}$/)

    if (wildcard) {
      const parent = path.join(projectPath, wildcard[1])
      const entries = await fs.promises
        .readdir(parent, { withFileTypes: true })
        .catch(() => [])

      for (const entry of entries) {
        if (entry.isDirectory()) {
          directories.push(path.join(parent, entry.name))
        }
      }
    } else {
      directories.push(path.join(projectPath, pattern))
    }
  }

  return directories
    .map((directory) => path.join(directory, 'package.json'))
    .filter((manifestPath) => fs.existsSync(manifestPath))
}

export async function updateResolutions(projectPath: string) {
  const packageManager = await detectPackageManager(projectPath)

  // Always use yarn to list Cedar framework packages. The monorepo is a yarn
  // workspace regardless of what package manager the user project uses.
  const rawList = (await $`yarn workspaces list --json`).stdout.trim()

  const workspaces = rawList
    .split('\n')
    .map((line) => JSON.parse(line))
    // Filter out the root workspace.
    .filter(({ name }) => name)

  const resolutions = workspaces.reduce<Record<string, string>>(
    (acc, { name }) => {
      // Turn a Cedar package name like `@cedarjs/project-config` into `cedarjs-project-config.tgz`.
      const tgzName = `${name.replace('@', '').replaceAll('/', '-')}.tgz`

      return {
        ...acc,
        [name]: `${projectPath}/${TARBALL_DEST_DIRNAME}/${tgzName}`,
      }
    },
    {},
  )

  const projectPackageJsonPath = path.join(projectPath, 'package.json')
  const projectPackageJson = JSON.parse(
    await fs.promises.readFile(projectPackageJsonPath, 'utf-8'),
  )

  const reactResolutions = await getReactResolutions()

  let updatedPackageJson: Record<string, unknown>

  if (packageManager === 'pnpm') {
    const allOverrides = {
      ...resolutions,
      ...reactResolutions,
      graphql: '16.13.2',
    }

    const pnpmWorkspacePath = path.join(projectPath, 'pnpm-workspace.yaml')
    let workspaceContent = await fs.promises.readFile(
      pnpmWorkspacePath,
      'utf-8',
    )

    const overrideLines = Object.entries(allOverrides)
      .map(([key, value]) => `  '${key}': '${value}'`)
      .join('\n')

    const overridesMatch = workspaceContent.match(/^(overrides:.*)$/m)
    if (overridesMatch) {
      const overrideStart = overridesMatch.index! + overridesMatch[0].length
      const afterHeader = workspaceContent.slice(overrideStart)
      const existingLines = afterHeader.split('\n')
      let lastOverrideLine = 0
      const overrideEnd = (() => {
        for (let i = 1; i < existingLines.length; i++) {
          if (/^\S/.test(existingLines[i]) && existingLines[i].trim()) {
            return i
          }
          if (/^\s+'.+':/.test(existingLines[i])) {
            lastOverrideLine = i
          }
        }
        return lastOverrideLine + 1
      })()

      const existingBlock = existingLines.slice(1, overrideEnd).join('\n')
      const existingKeys = new Set(
        existingBlock
          .split('\n')
          .map((l) => l.match(/^\s+'([^']+)':/)?.[1])
          .filter(Boolean),
      )

      const newLines = Object.entries(allOverrides)
        .filter(([key]) => !existingKeys.has(key))
        .map(([key, value]) => `  '${key}': '${value}'`)
        .join('\n')

      if (newLines) {
        const insertAt =
          overrideStart +
          existingLines.slice(0, lastOverrideLine + 1).join('\n').length

        workspaceContent =
          workspaceContent.slice(0, insertAt + 1) +
          '\n' +
          newLines +
          workspaceContent.slice(insertAt + 1)
      }
    } else {
      workspaceContent += '\noverrides:\n' + overrideLines + '\n'
    }

    await fs.promises.writeFile(pnpmWorkspacePath, workspaceContent)

    // Add direct dependencies for workspace packages that are normally
    // hoisted by yarn but need to be explicit for pnpm's strict isolation.
    const webPkgPath = path.join(projectPath, 'web/package.json')
    const webPkg = JSON.parse(await fs.promises.readFile(webPkgPath, 'utf-8'))
    webPkg.dependencies['graphql-tag'] = '2.12.6'
    webPkg.dependencies['react-hook-form'] = '7.74.0'

    const apiPkgPath = path.join(projectPath, 'api/package.json')
    const apiPkg = JSON.parse(await fs.promises.readFile(apiPkgPath, 'utf-8'))
    apiPkg.dependencies['@prisma/client'] = '7.8.0'

    // ESM projects have config, setup, and test files with imports that yarn
    // hoists to the project root but pnpm's strict isolation doesn't resolve:
    // web/vite.config.ts imports `vite`, web/vitest.setup.ts imports the
    // testing-library packages, test files import `@cedarjs/testing/web`, and
    // api/vitest.config.mts imports `vitest/config` and `@cedarjs/vite/api`.
    // Declare them all explicitly. (The `@cedarjs/*` specs are redirected to
    // the tarballs by the overrides written above, so the specs here are only
    // about being resolvable.)
    if (projectPackageJson.type === 'module') {
      const cedarSpec =
        webPkg.devDependencies?.['@cedarjs/vite'] ??
        webPkg.dependencies['@cedarjs/vite'] ??
        'latest'

      webPkg.devDependencies ??= {}
      webPkg.devDependencies.vite =
        projectPackageJson.resolutions?.vite ?? '7.3.5'
      webPkg.devDependencies['@cedarjs/testing'] =
        projectPackageJson.devDependencies?.['@cedarjs/testing'] ?? cedarSpec
      webPkg.devDependencies['@testing-library/jest-dom'] = '6.9.1'
      webPkg.devDependencies['@testing-library/react'] = '16.3.2'

      apiPkg.devDependencies ??= {}
      apiPkg.devDependencies.vitest =
        projectPackageJson.devDependencies?.vitest ?? '4.1.10'
      apiPkg.devDependencies['@cedarjs/vite'] = cedarSpec
      // The auto-imports transform injects `import { context } from
      // '@cedarjs/context'`, and the api templates import `gql` from
      // graphql-tag
      apiPkg.devDependencies['@cedarjs/context'] = cedarSpec
      apiPkg.dependencies['graphql-tag'] = '2.12.6'
    }

    await fs.promises.writeFile(webPkgPath, JSON.stringify(webPkg, null, 2))
    await fs.promises.writeFile(apiPkgPath, JSON.stringify(apiPkg, null, 2))

    updatedPackageJson = { ...projectPackageJson }
    delete updatedPackageJson.pnpm
  } else if (packageManager === 'npm') {
    // npm has no `resolutions` — the equivalent is `overrides`, which lives in
    // package.json like yarn's does.
    //
    // The tarball paths need an explicit `file:` prefix here. yarn and pnpm
    // both accept a bare absolute path, but npm parses an override value as a
    // version spec and won't recognise one.
    const tarballOverrides = Object.fromEntries(
      Object.entries(resolutions).map(([name, tarballPath]) => [
        name,
        `file:${tarballPath}`,
      ]),
    )

    // npm rejects an override for a package that is also a direct dependency
    // unless the two specs agree — `npm error code EOVERRIDE, Override for
    // @cedarjs/core@5.0.1 conflicts with direct dependency`. So point the
    // direct dependencies at the tarballs as well. The overrides are still
    // needed: they're what redirects the framework packages that are pulled
    // in transitively rather than declared
    // Every section npm treats as a direct dependency. `peerDependencies` is
    // deliberately left alone: a peer is a range the project requires of its
    // consumer, not something npm installs on its behalf, so rewriting one to
    // a `file:` path would be wrong
    const pointDirectDepsAtTarballs = (packageJson: Record<string, any>) => {
      for (const depsKey of [
        'dependencies',
        'devDependencies',
        'optionalDependencies',
      ]) {
        const deps = packageJson[depsKey]

        if (!deps) {
          continue
        }

        for (const name of Object.keys(deps)) {
          if (tarballOverrides[name]) {
            deps[name] = tarballOverrides[name]
          }
        }
      }
    }

    // Every workspace, not just the root — `@cedarjs/web` is a dependency of
    // web, `@cedarjs/api` of api, and so on. Derived from the root manifest
    // rather than hard-coded, so a Cedar dependency added to any other
    // workspace doesn't quietly keep a spec that conflicts with the overrides
    for (const workspacePkgPath of await findWorkspaceManifests(
      projectPath,
      projectPackageJson,
    )) {
      const workspacePkg = JSON.parse(
        await fs.promises.readFile(workspacePkgPath, 'utf-8'),
      )

      pointDirectDepsAtTarballs(workspacePkg)

      await fs.promises.writeFile(
        workspacePkgPath,
        JSON.stringify(workspacePkg, null, 2),
      )
    }

    pointDirectDepsAtTarballs(projectPackageJson)

    // Merged rather than replaced so that overrides the project already set
    // (react-is, for example) survive
    updatedPackageJson = {
      ...projectPackageJson,
      overrides: {
        ...projectPackageJson.overrides,
        ...tarballOverrides,
        ...reactResolutions,
      },
    }
  } else {
    updatedPackageJson = {
      ...projectPackageJson,
      resolutions: {
        ...projectPackageJson.resolutions,
        ...resolutions,
        ...reactResolutions,
      },
    }
  }

  await fs.promises.writeFile(
    projectPackageJsonPath,
    JSON.stringify(updatedPackageJson, null, 2),
  )
}

export async function getReactResolutions() {
  const packageConfig = JSON.parse(
    await fs.promises.readFile(
      path.join(FRAMEWORK_PATH, 'packages/web/package.json'),
      'utf-8',
    ),
  )

  const react = packageConfig.peerDependencies.react
  const reactDom = packageConfig.peerDependencies['react-dom']

  if (!react || !reactDom) {
    throw new Error(
      "Couldn't find react or react-dom in @cedarjs/web's peerDependencies",
    )
  }

  return {
    react,
    'react-dom': reactDom,
  }
}

export async function pmInstall(projectPath: string, verbose = false) {
  const packageManager = await detectPackageManager(projectPath)

  // npm runs a security audit and a funding lookup after every install. Both
  // are network round trips over the whole dependency tree, and neither tells
  // us anything about the framework build we're testing — skipping them takes
  // the install from ~78s to ~18s. yarn and pnpm don't do this by default
  const installArgs =
    packageManager === 'npm'
      ? ['install', '--no-audit', '--no-fund']
      : ['install']

  if (verbose) {
    console.log(
      `[tarsync] Running '${packageManager} ${installArgs.join(' ')}' in ${projectPath}`,
    )
  }
  const start = Date.now()

  await within(async () => {
    cd(projectPath)
    await $`${packageManager} ${installArgs}`
  })

  if (verbose) {
    const elapsed = Date.now() - start
    console.log(
      `[tarsync] '${packageManager} install' completed in ${elapsed}ms`,
    )
  }

  // Verify that the install actually produced a lockfile. On Windows the
  // install process can crash (e.g. V8 Maglev JIT bug, exit code 0xC0000409)
  // without zx detecting a non-zero exit code. If the lockfile is still
  // missing after install, fail loudly here rather than silently producing a
  // broken project that fails at a later, less obvious step.
  const lockfileName =
    packageManager === 'pnpm'
      ? 'pnpm-lock.yaml'
      : packageManager === 'npm'
        ? 'package-lock.json'
        : 'yarn.lock'

  const lockfilePath = path.join(projectPath, lockfileName)

  if (!fs.existsSync(lockfilePath)) {
    throw new Error(
      `[tarsync] '${packageManager} install' completed but ${lockfileName} was not created in ${projectPath}. ` +
        `The install process likely crashed silently (e.g. V8 Maglev JIT bug on Windows). ` +
        `Check the install output above for clues.`,
    )
  }

  if (verbose) {
    console.log(`[tarsync] ${lockfileName} exists after install — OK`)
  }
}
