import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { parseArgs as nodeUtilParseArgs } from 'node:util'

import ansis from 'ansis'
import { $, cd, glob, path, within } from 'zx'

export const TARBALL_DEST_DIRNAME = 'tarballs'

export const FRAMEWORK_PATH = fileURLToPath(
  new URL('../../../', import.meta.url),
)

export const IGNORE_EXTENSIONS = ['.DS_Store']

/**
 * Add to this array of strings, RegExps, or functions (whichever makes the most sense)
 * to ignore files that we don't want triggering package rebuilds.
 */
export const IGNORED = [
  /node_modules/,

  /packages\/codemods/,
  /packages\/create-cedar-app/,

  /dist/,

  /__fixtures__/,
  /__mocks__/,
  /__tests__/,
  /\.test\./,
  /jest.config.{js,ts}/,

  /README.md/,

  // esbuild emits meta.json files that we sometimes suffix.
  /meta.(\w*\.?)json/,

  /tsconfig.tsbuildinfo/,
  /tsconfig.build.tsbuildinfo/,
  /tsconfig.cjs.tsbuildinfo/,

  // The tarballs generated by `yarn build:pack`
  /cedar-.*\.tgz$/,

  (filePath: string) => IGNORE_EXTENSIONS.some((ext) => filePath.endsWith(ext)),
]

export interface Options {
  projectPath: string
  watch: boolean
  verbose: boolean
}

export async function getOptions(): Promise<Options> {
  const { positionals, values } = nodeUtilParseArgs({
    allowPositionals: true,
    options: {
      verbose: {
        type: 'boolean',
        default: false,
        short: 'v',
      },
      watch: {
        type: 'boolean',
        default: false,
        short: 'w',
      },
    },
  })
  const [projectPath] = positionals

  const options: Options = {
    projectPath:
      projectPath ?? process.env.CEDAR_CWD ?? process.env.RWJS_CWD ?? '',
    watch: values.watch ?? false,
    verbose: values.verbose ?? false,
  }

  if (!options.projectPath) {
    throw new Error(
      [
        'Error: You have to provide the path to a Cedar project as',
        '',
        '  1. the first positional argument',
        '',
        ansis.gray('  yarn project:tarsync /path/to/cedar/project'),
        '',
        '  2. the `CEDAR_CWD` env var',
        '',
        ansis.gray('  CEDAR_CWD=/path/to/cedar/project yarn project:tarsync'),
      ].join('\n'),
    )
  }

  // This makes `projectPath` an absolute path and throws if it doesn't exist.
  options.projectPath = await fs.promises.realpath(options.projectPath)

  return options
}

export async function buildTarballs() {
  await $`yarn nx run-many -t build:pack --exclude create-cedar-app`
}

export async function copyTarballs(projectPath: string) {
  const tarballDest = path.join(projectPath, TARBALL_DEST_DIRNAME)
  await fs.promises.mkdir(tarballDest, { recursive: true })

  const tarballs = await glob(['./packages/**/*.tgz'])

  await Promise.all(
    tarballs.map(async (tarball) => {
      const dest = path.join(tarballDest, path.basename(tarball))
      await fs.promises.copyFile(tarball, dest)
    }),
  )
}

export async function updateResolutions(projectPath: string) {
  const resolutions = (await $`yarn workspaces list --json`).stdout
    .trim()
    .split('\n')
    .map((line) => JSON.parse(line))
    // Filter out the root workspace.
    .filter(({ name }) => name)
    .reduce((resolutions, { name }) => {
      return {
        ...resolutions,
        // Turn a Cedar package name like `@cedarjs/project-config` into `cedarjs-project-config.tgz`.
        [name]: `./${TARBALL_DEST_DIRNAME}/${
          name.replace('@', '').replaceAll('/', '-') + '.tgz'
        }`,
      }
    }, {})

  const projectPackageJsonPath = path.join(projectPath, 'package.json')
  const projectPackageJson = JSON.parse(
    await fs.promises.readFile(projectPackageJsonPath, 'utf-8'),
  )

  await fs.promises.writeFile(
    projectPackageJsonPath,
    JSON.stringify(
      {
        ...projectPackageJson,
        resolutions: {
          ...projectPackageJson.resolutions,
          ...resolutions,
          ...(await getReactResolutions()),
        },
      },
      null,
      2,
    ),
  )
}

export async function getReactResolutions() {
  const packageConfig = JSON.parse(
    await fs.promises.readFile(
      path.join(FRAMEWORK_PATH, 'packages/web/package.json'),
      'utf-8',
    ),
  )

  const react = packageConfig.peerDependencies.react
  const reactDom = packageConfig.peerDependencies['react-dom']

  if (!react || !reactDom) {
    throw new Error(
      "Couldn't find react or react-dom in @cedarjs/web's peerDependencies",
    )
  }

  return {
    react,
    'react-dom': reactDom,
  }
}

export async function yarnInstall(projectPath: string) {
  await within(async () => {
    cd(projectPath)
    await $`yarn install`
  })
}
