// This file was generated by CedarJS
import AboutPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/AboutPage/AboutPage'
import BlogPostPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/BlogPostPage/BlogPostPage'
import ContactUsPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/ContactUsPage/ContactUsPage'
import DoublePageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/DoublePage/DoublePage'
import FatalErrorPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import HomePageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/HomePage/HomePage'
import LoginPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/LoginPage/LoginPage'
import NotFoundPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/NotFoundPage/NotFoundPage'
import ProfilePageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/ProfilePage/ProfilePage'
import ResetPasswordPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/ResetPasswordPage/ResetPasswordPage'
import SignupPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/SignupPage/SignupPage'
import WaterfallPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/WaterfallPage/WaterfallPage'
import ContactContactPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/Contact/ContactPage/ContactPage'
import ContactContactsPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/Contact/ContactsPage/ContactsPage'
import ContactEditContactPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/Contact/EditContactPage/EditContactPage'
import ContactNewContactPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/Contact/NewContactPage/NewContactPage'
import PostEditPostPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/Post/EditPostPage/EditPostPage'
import PostNewPostPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/Post/NewPostPage/NewPostPage'
import PostPostPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/Post/PostPage/PostPage'
import PostPostsPageType from '/Users/tobbe/dev/cedarjs/cedar/test-project/web/src/pages/Post/PostsPage/PostsPage'

declare global {
  const AboutPage: typeof AboutPageType
  const BlogPostPage: typeof BlogPostPageType
  const ContactUsPage: typeof ContactUsPageType
  const DoublePage: typeof DoublePageType
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const HomePage: typeof HomePageType
  const LoginPage: typeof LoginPageType
  const NotFoundPage: typeof NotFoundPageType
  const ProfilePage: typeof ProfilePageType
  const ResetPasswordPage: typeof ResetPasswordPageType
  const SignupPage: typeof SignupPageType
  const WaterfallPage: typeof WaterfallPageType
  const ContactContactPage: typeof ContactContactPageType
  const ContactContactsPage: typeof ContactContactsPageType
  const ContactEditContactPage: typeof ContactEditContactPageType
  const ContactNewContactPage: typeof ContactNewContactPageType
  const PostEditPostPage: typeof PostEditPostPageType
  const PostNewPostPage: typeof PostNewPostPageType
  const PostPostPage: typeof PostPostPageType
  const PostPostsPage: typeof PostPostsPageType
}

//# sourceMappingURL=web-routesPages.d.ts.map
