// This file was generated by CedarJS
import { RouteParams, QueryParams } from '@cedarjs/router'

declare module '@cedarjs/router' {
  interface AvailableRoutes {
    // Only "<Route />" components with a "name" and "path" prop will be populated here.
    double: (params?: RouteParams<"/double"> & QueryParams) => "/double"
    login: (params?: RouteParams<"/login"> & QueryParams) => "/login"
    signup: (params?: RouteParams<"/signup"> & QueryParams) => "/signup"
    forgotPassword: (params?: RouteParams<"/forgot-password"> & QueryParams) => "/forgot-password"
    resetPassword: (params?: RouteParams<"/reset-password"> & QueryParams) => "/reset-password"
    newContact: (params?: RouteParams<"/contacts/new"> & QueryParams) => "/contacts/new"
    editContact: (params?: RouteParams<"/contacts/{id:Int}/edit"> & QueryParams) => "/contacts/{id:Int}/edit"
    contact: (params?: RouteParams<"/contacts/{id:Int}"> & QueryParams) => "/contacts/{id:Int}"
    contacts: (params?: RouteParams<"/contacts"> & QueryParams) => "/contacts"
    newPost: (params?: RouteParams<"/posts/new"> & QueryParams) => "/posts/new"
    editPost: (params?: RouteParams<"/posts/{id:Int}/edit"> & QueryParams) => "/posts/{id:Int}/edit"
    post: (params?: RouteParams<"/posts/{id:Int}"> & QueryParams) => "/posts/{id:Int}"
    posts: (params?: RouteParams<"/posts"> & QueryParams) => "/posts"
    waterfall: (params?: RouteParams<"/waterfall/{id:Int}"> & QueryParams) => "/waterfall/{id:Int}"
    profile: (params?: RouteParams<"/profile"> & QueryParams) => "/profile"
    blogPost: (params?: RouteParams<"/blog-post/{id:Int}"> & QueryParams) => "/blog-post/{id:Int}"
    contactUs: (params?: RouteParams<"/contact"> & QueryParams) => "/contact"
    about: (params?: RouteParams<"/about"> & QueryParams) => "/about"
    home: (params?: RouteParams<"/"> & QueryParams) => "/"
  }

  export function useRoutePaths(): Record<keyof AvailableRoutes, string>
  export function useRoutePath(routeName: keyof AvailableRoutes): string

  /** Gets the name of the current route (as defined in your Routes file) */
  export function useRouteName(): keyof AvailableRoutes | undefined
}

//# sourceMappingURL=web-routerRoutes.d.ts.map
