/**
 * End-to-end regression test for the Prisma 7 `prisma-client` generator
 * provider scenario.
 *
 * Prisma 7's new `prisma-client` provider deliberately stops exporting
 * `Prisma.ModelName` at runtime, which is what `@cedarjs/internal`'s codegen
 * previously relied on to populate its GraphQL `mappers` config. Without that
 * record, codegen used to emit a `graphql.d.ts` with empty mappers — every
 * resolver typed against `unknown`, every relation collapsed to `never` —
 * which only surfaced as hundreds of type errors when the project ran
 * `cedar type-check` downstream.
 *
 * This file exercises the actual codegen output (not just the helper in
 * isolation) so a future regression in the schema-parsing fallback would
 * fail this test rather than silently producing broken types.
 */
import fs from 'node:fs'
import path from 'node:path'

const { mockPrismaClientPath, mockPrismaClientFileUrl } = await vi.hoisted(
  async () => {
    const p = await import('node:path')
    const { pathToFileURL } = await import('node:url')

    const mockPrismaClientPath = p.resolve('/mock-prisma-client-path')
    const mockPrismaClientFileUrl = pathToFileURL(mockPrismaClientPath)
    return { mockPrismaClientPath, mockPrismaClientFileUrl }
  },
)

import { afterAll, afterEach, beforeAll, expect, test, vi } from 'vitest'

import type * as ProjectConfig from '@cedarjs/project-config'

import { generateTypeDefGraphQLApi } from '../generate/graphqlCodeGen.js'
import { generateGraphQLSchema } from '../generate/graphqlSchema.js'

const FIXTURE_PATH = path.resolve(
  __dirname,
  '../../../../__fixtures__/example-todo-main',
)

beforeAll(() => {
  process.env.CEDAR_CWD = FIXTURE_PATH
})

afterAll(() => {
  delete process.env.CEDAR_CWD
})

afterEach(() => {
  vi.restoreAllMocks()
})

vi.mock('@cedarjs/project-config', async (importOriginal) => {
  const original = await importOriginal<typeof ProjectConfig>()
  const p = await import('node:path')

  return {
    ...original,
    resolveGeneratedPrismaClient: () =>
      Promise.resolve({ clientPath: mockPrismaClientPath, error: undefined }),
    // The `example-todo-main` fixture predates Prisma's `prisma.config.{ts,cjs}`
    // style, so `loadPrismaConfig` (called by the real `getSchemaPath`) would
    // throw on the missing config file. Short-circuit it to the fixture's
    // actual schema path — the rest of the schema-fallback pipeline still
    // runs against real `fs` against a real schema file.
    getSchemaPath: () =>
      Promise.resolve(
        p.resolve(
          __dirname,
          '../../../../__fixtures__/example-todo-main/api/prisma/schema.prisma',
        ),
      ),
  }
})

// Stub `execa` so that the intermediate `cedar prisma generate` shell-out in
// `getPrismaClient` is a no-op — we don't want this test to actually invoke
// the CLI.
vi.mock('execa', () => {
  return {
    default: {
      sync: vi.fn(),
    },
  }
})

const mockNow = vi.hoisted(() => new Date().getTime())

// Crucially, the mocked Prisma client *omits* `ModelName`. This is what the
// Prisma 7 `prisma-client` generator produces at runtime and is the exact
// shape that previously caused codegen to emit empty mappers.
vi.mock(mockPrismaClientFileUrl + '?t=' + mockNow, () => {
  return {
    Prisma: {
      // intentionally no `ModelName`
    },
  }
})

test('codegen recovers ModelName from schema when Prisma client omits it', async () => {
  await generateGraphQLSchema()

  vi.setSystemTime(mockNow)

  let codegenOutput: {
    file: fs.PathOrFileDescriptor
    data: string | ArrayBufferView
  } = { file: '', data: '' }

  vi.spyOn(fs, 'writeFileSync').mockImplementation(
    (file: fs.PathOrFileDescriptor, data: string | ArrayBufferView) => {
      codegenOutput = { file, data }
    },
  )

  const { typeDefFiles, errors } = await generateTypeDefGraphQLApi()
  expect(errors).toEqual([])
  expect(typeDefFiles).toHaveLength(1)

  const data = String(codegenOutput.data)

  // The fixture's `schema.prisma` declares a single `Todo` model. With the
  // schema-parsing fallback wired in, the codegen output should import it
  // from prisma and use it in the resolver mapper aliases — even though the
  // mocked Prisma client doesn't expose `ModelName`.
  expect(data).toContain("import { Todo as PrismaTodo } from 'src/lib/db'")

  // `AllMappedModels` is generated by `printMappedModelsPlugin` and is the
  // strongest single signal that mappers came through. An empty mapper map
  // produces `MaybeOrArrayOfMaybe<>` here; a working one produces
  // `MaybeOrArrayOfMaybe<Todo>`.
  expect(data).toContain('type AllMappedModels = MaybeOrArrayOfMaybe<Todo>')

  // And the negative assertion — make sure we don't regress back to the
  // empty-mapper output.
  expect(data).not.toContain('type AllMappedModels = MaybeOrArrayOfMaybe<>')
})
