// This file was generated by CedarJS
import { default as DEFAULT } from './ClassWithClassField.js'
export default DEFAULT
export * from './ClassWithClassField.js'

//# sourceMappingURL=index.d.ts.map
