import { getPackageManager } from '@cedarjs/project-config/packageManager'

import type { Monitor } from '../../../deploy/baremetal/monitors.js'

/** Where the generated systemd unit files live in the project */
export const SYSTEMD_DIR = 'systemd'

/** Path of the jobs worker bin, relative to the project root */
const JOBS_WORKER_BIN = 'api/node_modules/.bin/cedar-jobs-worker'

/**
 * How long a monitor waits for a jobs worker to finish its current job after
 * asking it to stop, before killing it
 */
const WORKER_STOP_TIMEOUT_SECONDS = 600

const JOBS_WORKER_COMMENT = `# Runs one background jobs worker. \`--index\` picks the entry of the \`workers\`
# array in api/src/lib/jobs.ts and \`--id\` numbers the worker within that
# entry, so an entry with \`count: 2\` needs a second worker with \`--id=1\`.`

/**
 * pm2 ecosystem file with a `serve` app and, when the project has background
 * jobs set up, a `jobs` app for one worker.
 */
export const ecosystemConfig = ({ jobs }: { jobs: boolean }) => {
  const jobsApp = jobs
    ? `
    {
      // Runs one background jobs worker. \`--index\` picks the entry of the
      // \`workers\` array in api/src/lib/jobs.ts and \`--id\` numbers the worker
      // within that entry, so an entry with \`count: 2\` needs a second app
      // with \`--id=1\`.
      name: 'jobs',
      cwd: 'current',
      script: '${JOBS_WORKER_BIN}',
      args: '--index=0 --id=0',
      // pm2 stops the worker with SIGINT, which lets it finish the job it is
      // running. This is how long pm2 waits for that (in ms) before killing it.
      kill_timeout: ${WORKER_STOP_TIMEOUT_SECONDS * 1000},
    },`
    : ''

  return `module.exports = {
  apps: [
    {
      name: 'serve',
      cwd: 'current',
      script: 'node_modules/.bin/cedar',
      args: 'serve',
      instances: 'max',
      exec_mode: 'cluster',
      wait_ready: true,
      listen_timeout: 10000,
    },${jobsApp}
  ],
}
`
}

const unitHeader = (appName: string, monitor: Monitor) => {
  const install =
    monitor === 'systemd-system'
      ? `#   sudo cp ${SYSTEMD_DIR}/*.service /etc/systemd/system/`
      : `#   mkdir -p ~/.config/systemd/user && cp ${SYSTEMD_DIR}/*.service ~/.config/systemd/user/`

  const linger =
    monitor === 'systemd-system'
      ? ''
      : `#
# User units only run while the user has a session, so let them run after a
# reboot too:
#   sudo loginctl enable-linger $(whoami)
`

  return `# systemd unit for the ${appName} Cedar app, generated by \`cedar setup deploy baremetal\`.
#
# Copy the unit files to the server once, before the first deploy:
${install}
${linger}#
# Then deploy with \`--first-run\`, which reloads the unit files and enables and
# starts every process listed in deploy.toml.
#
# WorkingDirectory must be the \`path\` from deploy.toml followed by \`/current\`.`
}

const unitService = (
  monitor: Monitor,
  execStart: string,
  extraDirectives = '',
) => {
  const user = monitor === 'systemd-system' ? '\nUser=deploy' : ''

  return `[Service]
WorkingDirectory=/var/www/app/current
# A login shell puts node and ${getPackageManager()} from a version manager such as nvm on the PATH
ExecStart=/bin/bash -lc '${execStart}'
Restart=always
RestartSec=5
Environment=NODE_ENV=production${user}${extraDirectives}`
}

// Stopping a jobs worker with SIGINT lets it finish the job it is running
const JOBS_STOP_DIRECTIVES = `
# Stopping sends SIGINT so the worker finishes the job it is running before it
# exits. systemd waits this long for that before killing the worker.
KillSignal=SIGINT
TimeoutStopSec=${WORKER_STOP_TIMEOUT_SECONDS}`

const unitInstall = (monitor: Monitor) =>
  `[Install]
WantedBy=${monitor === 'systemd-system' ? 'multi-user.target' : 'default.target'}`

/** systemd unit that runs `cedar serve` */
export const systemdServiceUnit = ({
  appName,
  monitor,
}: {
  appName: string
  monitor: Monitor
}) => `${unitHeader(appName, monitor)}

[Unit]
Description=${appName} (Cedar)
After=network.target

${unitService(monitor, 'exec node_modules/.bin/cedar serve')}

${unitInstall(monitor)}
`

/**
 * Template unit for background jobs workers. Each instance name is the index
 * of a `workers` entry, so `<app>-jobs@0` runs a worker for the first entry.
 */
export const systemdJobsUnit = ({
  appName,
  monitor,
}: {
  appName: string
  monitor: Monitor
}) => `${unitHeader(appName, monitor)}
#
${JOBS_WORKER_COMMENT}
# Start one instance per \`workers\` entry: \`${appName}-jobs@0\`, \`${appName}-jobs@1\`
# and so on, and list each one in \`processNames\` in deploy.toml.

[Unit]
Description=${appName} background jobs worker %i (Cedar)
After=network.target

${unitService(monitor, `exec ${JOBS_WORKER_BIN} --index=%i --id=0`, JOBS_STOP_DIRECTIVES)}

${unitInstall(monitor)}
`

/** deploy.toml for the chosen monitor and the processes it manages */
export const deployToml = ({
  monitor,
  processNames,
}: {
  monitor: Monitor
  processNames: string[]
}) => `# This file contains config for a baremetal deployment
#
# SSH connection options include:
#
# * host - the remote server hostname/IP
# * port - defaults to 22
# * username - required, the user you're connecting as
# * password - only set if you're not using key-based authentication
# * privateKey - a Buffer containing the private key (use this _or_ \'privateKeyPath\', not both)
# * privateKeyPath - local file path to a private key that will be sent with the connection request
# * passphrase - used if your private key has a passphrase
# * agentForward - set to \`true\` to forward the client machine's ssh credentials
#
# Process monitor options:
#
# * monitor - "pm2", "systemd-user" or "systemd-system". Decides how processes
#   are started for the first time, restarted and stopped
# * monitorCommand - overrides the command the monitor is invoked with. Defaults
#   to \`pm2\`, \`systemctl --user\` or \`sudo systemctl\` depending on \`monitor\`,
#   for example \`doppler run -- pm2\`
# * processNames - the pm2 app names or systemd unit names to (re)start
#
# After restarting the processes, the deploy requests the api side's health
# check endpoint on the server and fails if it doesn't respond in time:
#
# * healthCheckUrl - defaults to http://localhost:<[api].port>/graphql/health
#   on servers that host the api side. Set to \`false\` to skip the check
# * healthCheckTimeout - seconds to keep retrying, defaults to 30
#
# See https://cedarjs.com/docs/deploy/baremetal for more info

[[production.servers]]
host = "server.com"
username = "user"
agentForward = true
sides = ["api","web"]
packageManagerCommand = "${getPackageManager()}"
monitor = "${monitor}"
path = "/var/www/app"
processNames = [${processNames.map((name) => `"${name}"`).join(', ')}]
repo = "git@github.com:myorg/myapp.git"
branch = "main"
keepReleases = 5
freeSpaceRequired = 2048
healthCheckTimeout = 30

# If you have separate api and web servers:
#
# [[production.servers]]
# host = "api.server.com"
# username = "user"
# agentForward = true
# sides = ["api"]
# path = "/var/www/app"
# repo = "git@github.com:cedarjs/cedar.git"
# branch = "main"
# processNames = ["api"]
#
# [[production.servers]]
# host = "web.server.com"
# username = "user"
# agentForward = true
# sides = ["web"]
# path = "/var/www/app"
# repo = "git@github.com:cedarjs/cedar.git"
# branch = "main"
# migrate = false # only one server in a cluster needs to migrate
# processNames = ["web"]
`

export const MAINTENANCE = `<!--
Put up this maintenance page on your deployed service with:

  yarn cedar baremetal deploy --maintenance up

And take it back down with:

  yarn cedar baremetal deploy --maintenance down
-->

<!DOCTYPE html>
<html>
  <head>
    <title>Maintenance</title>
    <style>
      html, body {
        margin: 0;
      }
      html * {
        box-sizing: border-box;
      }
      main {
        display: flex;
        align-items: center;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif;
        text-align: center;
        background-color: #E2E8F0;
        height: 100vh;
      }
      section {
        background-color: white;
        border-radius: 0.25rem;
        width: 36rem;
        padding: 1rem;
        margin: 0 auto;
        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
      }
      h1 {
        font-size: 2rem;
        margin: 0;
        font-weight: 500;
        line-height: 1;
        color: #2D3748;
      }
    </style>
  </head>
  <body>
    <main>
      <section>
        <h1>
          <span>Maintenance Mode: Be Back Soon</span>
        </h1>
      </section>
    </main>
  </body>
</html>
`
