/**
 * Public setup API for gqlorm.
 *
 * Call `configureGqlorm()` once at app startup — typically at the top of
 * `App.tsx` or in a dedicated bootstrap file — before any `useLiveQuery`
 * invocations.
 *
 * @example
 * import { configureGqlorm } from '@cedarjs/gqlorm/setup'
 * import schema from '.cedar/gqlorm-schema.json'
 *
 * configureGqlorm({ schema })
 */

import { queryBuilder } from './queryBuilder.js'
import type { ModelSchema } from './types/schema.js'

export interface ConfigureGqlormOptions {
  /**
   * The model schema mapping lowercase model names to their visible scalar
   * field names. Typically imported from `.cedar/gqlorm-schema.json`, which
   * is auto-generated by Cedar's codegen pipeline.
   *
   * When `undefined`, gqlorm falls back to requesting only the `id` field in
   * auto-generated queries (the behaviour before any schema is configured).
   * Passing `undefined` explicitly is useful in test environments where a
   * full schema is not available.
   */
  schema: ModelSchema | undefined
}

/**
 * Configure gqlorm at app startup.
 *
 * Applies the provided `ModelSchema` to the global `queryBuilder` singleton so
 * that `useLiveQuery((db) => db.post.findMany())` — with no explicit `select`
 * — generates a GraphQL query requesting all visible scalar fields for the
 * model instead of only `id`.
 *
 * The call is idempotent and safe to invoke multiple times; the last call wins.
 */
export function configureGqlorm(options: ConfigureGqlormOptions): void {
  queryBuilder.configure({ schema: options.schema })
}
