import path from 'node:path'

// unimport/unplugin is ESM-only. CJS builds double-wrap its default export:
// unimportPluginMod.default is the module object, and
// unimportPluginMod.default.default is the actual plugin object.
// The `||` chain resolves correctly for both.
import unimportPluginMod from 'unimport/unplugin'
const unimportPlugin =
  // @ts-expect-error – .default only exists at runtime in CJS double-wrap
  // interop
  unimportPluginMod.default?.default ||
  // @ts-expect-error – .default only exists at runtime in CJS double-wrap
  // interop
  unimportPluginMod.default ||
  unimportPluginMod
import autoImport from 'unplugin-auto-import/vite'

import {
  getConfig,
  getPaths,
  importStatementPath,
} from '@cedarjs/project-config'

export function cedarAutoImportsPlugin() {
  // Need the project config to know if trusted graphql documents is being used
  // and decide to use the gql tag import or the trusted document gql function
  // generated by code gen client preset
  const config = getConfig()
  const cedarPaths = getPaths()
  const useTrustedDocumentsGqlTag = config?.graphql?.trustedDocuments

  return [
    autoImport({
      // targets to transform
      include: [
        /web\/.*\.[tj]sx?$/,
        // Assume we want the trusted documents gql tag import in all .jsx and
        // .tsx files
        /\.[tj]sx$/,
      ],

      // global imports to register
      imports: [
        // import gql from 'graphql-tag'
        !useTrustedDocumentsGqlTag && {
          'graphql-tag': ['gql'],
        },
        // import { gql } from 'src/graphql/gql'
        useTrustedDocumentsGqlTag && {
          [importStatementPath(
            path.join(cedarPaths.web.base, 'src', 'graphql', 'gql'),
          )]: ['gql'],
        },
      ].filter(<T>(v?: T | false): v is T => Boolean(v)),

      // Types aren't important since the output is ephemeral
      dts: false,
    }),
    autoImport({
      // targets to transform
      //
      // This must stay scoped to api/ only. @cedarjs/context relies on
      // Node's AsyncLocalStorage, which isn't available in the browser.
      // If this ever matches web/ files too, an unrelated identifier
      // named `context` in a web-side file (e.g. a function parameter)
      // would get auto-imported from @cedarjs/context, pulling
      // AsyncLocalStorage into the web build and breaking it. See #2892.
      include: [/api\/.*\.[tj]sx?$/],

      // global imports to register
      imports: [
        {
          '@cedarjs/context': ['context'],
        },
      ],

      // Types aren't important since the output is ephemeral
      dts: false,
    }),
    autoImport({
      // targets to transform
      include: [/api\/.*\.[tj]sx?$/],

      // global imports to register
      imports: [
        // import gql from 'graphql-tag'
        {
          'graphql-tag': ['gql'],
        },
      ],

      // Types aren't important since the output is ephemeral
      dts: false,
    }),
    unimportPlugin.vite({
      imports: [
        // import React from 'react'
        {
          name: 'default',
          as: 'React',
          from: 'react',
        },
      ],
    }),
  ]
}
