// This file was generated by CedarJS
import * as Cell from './PostCell.js'
import type { CellProps } from '@cedarjs/web'
import type { FindPostById, FindPostByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './PostCell.js'

type CellInputs = CellProps<SuccessType, FindPostById, typeof Cell, FindPostByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
