// This file was generated by CedarJS
import * as Cell from './ContactsCell.js'
import type { CellProps } from '@cedarjs/web'
import type { FindContacts, FindContactsVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ContactsCell.js'

type CellInputs = CellProps<SuccessType, FindContacts, typeof Cell, FindContactsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
