packages:
  - api
  - web

allowBuilds:
  '@clerk/shared': false
  '@firebase/util': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  core-js: true
  core-js-pure: true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  unrs-resolver: false

overrides:
  'react-is': '19.2.3'
