import fs from 'node:fs'
import path from 'node:path'

const ___dirname = import.meta.dirname

/**
 * Write the contents of the template to the destination and interpolate the variables.
 * The template is a string that uses standard es6 template literals which allow embded expression.
 */
export const writeTemplate = (
  templatePath: string,
  destination: string,
  templateValues: Record<string, unknown> = {},
) => {
  const templateString = fs.readFileSync(
    path.join(___dirname, templatePath),
    'utf-8',
  )

  const template = templatized(templateString, templateValues)
  fs.writeFileSync(
    destination,
    '// This file was generated by CedarJS\n' + template,
  )
}

const templatized = (template: string, vars = {}) => {
  // eslint-disable-next-line @typescript-eslint/no-implied-eval
  const handler = new Function(
    'vars',
    [
      'const tagged = ( ' + Object.keys(vars).join(', ') + ' ) =>',
      '`' + template + '`',
      'return tagged(...Object.values(vars))',
    ].join('\n'),
  )

  return handler(vars)
}
