name: 🏗 Build, Lint, Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build-lint-test:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Remove the tsc problem matcher if not ubuntu-latest
        if: inputs.os != 'ubuntu-latest'
        run: echo "echo "::remove-matcher owner=tsc::""

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up job
        uses: ./.github/actions/set-up-job

      - name: 🔎 Lint
        run: yarn lint

      # TODO(jgmw): Re-enable when it doesn't hang
      # - name: 🥡 Check packaging and attw
      #   run: yarn check:package

      - name: 🌡 Test Types
        run: yarn test:types

      - name: Get number of CPU cores
        if: always()
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@97330871fe1b7d3529392ea000e3d2c4b357e403 # v3

      - name: 🧪 Test
        run: yarn test-ci --minWorkers=1 --maxWorkers=${{ steps.cpu-cores.outputs.count }}
