name: Cache Investigation
on:
  workflow_dispatch:
    inputs:
      investigation_type:
        description: 'Type of investigation to run'
        required: true
        default: 'quick'
        type: choice
        options:
          - quick
          - full
          - cache-only
          - env-only

jobs:
  investigate:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: ⬢ Enable Corepack
        run: npm install --global --force corepack

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          yarn install --frozen-lockfile --inline-builds
          yarn --cwd packages/create-cedar-rsc-app install --inline-builds

      - name: Run Cache Investigation
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
          YARN_ENABLE_HARDENED_MODE: 0
        run: |
          echo "🔍 Starting cache investigation: ${{ inputs.investigation_type }}"
          case "${{ inputs.investigation_type }}" in
            "quick")
              yarn tsx tasks/framework-tools/tarsync/debug-master.mts quick
              ;;
            "full")
              yarn tsx tasks/framework-tools/tarsync/debug-master.mts all
              ;;
            "cache-only")
              yarn tsx tasks/framework-tools/tarsync/debug-cache-investigation.mts
              ;;
            "env-only")
              yarn tsx tasks/framework-tools/tarsync/debug-env-differences.mts
              ;;
          esac

      - name: Upload Investigation Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cache-investigation-reports
          path: |
            cache-investigation-report.json
            environment-analysis-report.json
            task-scheduling-report.json
          retention-days: 30

      - name: Debug Investigation Failure
        if: failure()
        run: |
          echo "=== Investigation Debug Info ==="
          ls -la *-report.json || echo "No reports generated"
          df -h
          free -h
          echo "=== Nx Cache Status ==="
          ls -la .nx/cache || echo "No cache directory"
          echo "=== Directory structure ==="
          ls -la
