name: 📄 Fragments Smoke Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  fragments-smoke-tests:
    runs-on: ${{ inputs.os }}

    env:
      REDWOOD_CI: 1
      REDWOOD_VERBOSE_TELEMETRY: 1

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up job
        uses: ./.github/actions/set-up-job

      - name: 🌲 Set up test project
        id: set-up-test-project
        uses: ./.github/actions/set-up-test-project
        with:
          canary: true
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Run Fragments codemods on test project
        run: npx -y tsx ./tasks/test-project/add-gql-fragments ${{ steps.set-up-test-project.outputs.test-project-path }}
        env:
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: 🎭 Install playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: Run Fragments dev smoke tests
        working-directory: ./tasks/smoke-tests/fragments-dev
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: '${{ steps.set-up-test-project.outputs.test-project-path }}'
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: Build for production
        working-directory: ${{ steps.set-up-test-project.outputs.test-project-path }}
        run: yarn rw build
        env:
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: Run Fragments serve smoke tests
        working-directory: ./tasks/smoke-tests/fragments-serve
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: '${{ steps.set-up-test-project.outputs.test-project-path }}'
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: Enable trusted-documents in Fragments test project
        run: npx -y tsx ./tasks/test-project/set-up-trusted-documents ${{ steps.set-up-test-project.outputs.test-project-path }}
        env:
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: 📄 Run prerender smoke tests against Fragments test project (with trusted-documents enabled)
        working-directory: tasks/smoke-tests/prerender
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: ${{ steps.set-up-test-project.outputs.test-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1
