name: 🔄 Live Smoke Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  live-smoke-tests:
    runs-on: ${{ inputs.os }}

    env:
      REDWOOD_CI: 1
      REDWOOD_VERBOSE_TELEMETRY: 1

    steps:
      - name: Checkout the framework code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up job
        uses: ./.github/actions/set-up-job

      - name: 🌲 Set up test project (live)
        id: set-up-test-project
        uses: ./.github/actions/set-up-test-project-live
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: 🎭 Install playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: 🔄 Run live smoke tests
        working-directory: ./tasks/smoke-tests/live
        run: npx playwright test
        env:
          CEDAR_TEST_PROJECT_PATH: ${{ steps.set-up-test-project.outputs.test-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1
