name: 🔄🐘 RSC Smoke Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  rsc-smoke-tests:
    name: 🔄🐘 RSC Smoke tests / ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    env:
      REDWOOD_CI: 1
      REDWOOD_VERBOSE_TELEMETRY: 1

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up job
        uses: ./.github/actions/set-up-job

      - name: 🌲 Set up RSC project
        id: set-up-rsc-project
        uses: ./.github/actions/set-up-rsc-project
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: 🎭 Install playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: 🐘 Run RSC serve smoke tests
        working-directory: tasks/smoke-tests/rsc
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: ${{ steps.set-up-rsc-project.outputs.rsc-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1

      # TODO (RSC): This workflow times out on Windows. It looks as if the dev
      # server starts up ok, but it doesn't seem like the browser is rendering
      # what it should be. And now it's also started failing on Ubuntu. So I've
      # disabled it for now. The error on Ubuntu is:
      #   Failed to read a RSC payload created by a development version of
      #   React on the server while using a production version on the client.
      #   Always use matching versions on the server and the client.
      - name: 🐘 Run RSC dev smoke tests
        if: inputs.os == 'false__ubuntu-latest'
        working-directory: tasks/smoke-tests/rsc-dev
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: ${{ steps.set-up-rsc-project.outputs.rsc-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: 🌲 Set up RSA smoke test
        id: set-up-rsa-project
        uses: ./.github/actions/set-up-rsa-project
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: 🐘 Run RSA smoke tests
        working-directory: tasks/smoke-tests/rsa
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: ${{ steps.set-up-rsa-project.outputs.test-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: 🌲 Set up RSC Kitchen Sink smoke test
        id: set-up-rsc-kitchen-sink-project
        uses: ./.github/actions/set-up-rsc-kitchen-sink-project
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: 🐘 Run RSC Kitchen Sink smoke tests
        working-directory: tasks/smoke-tests/rsc-kitchen-sink
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: ${{ steps.set-up-rsc-kitchen-sink-project.outputs.test-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1
