name: 🔄 Smoke Tests Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  smoke-tests:
    runs-on: ${{ inputs.os }}

    env:
      REDWOOD_CI: 1
      REDWOOD_VERBOSE_TELEMETRY: 1

    steps:
      - name: Checkout the framework code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up job
        uses: ./.github/actions/set-up-job

      - name: 🌲 Set up test project
        id: set-up-test-project
        uses: ./.github/actions/set-up-test-project
        env:
          REDWOOD_DISABLE_TELEMETRY: 1
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: 🎭 Install playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: 🧑‍💻 Run dev smoke tests
        working-directory: ./tasks/smoke-tests/dev
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: '${{ steps.set-up-test-project.outputs.test-project-path }}'
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: 🔐 Run auth smoke tests
        working-directory: ./tasks/smoke-tests/auth
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: ${{ steps.set-up-test-project.outputs.test-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: Run `rw build --no-prerender`
        run: |
          yarn rw build --no-prerender
        working-directory: ${{ steps.set-up-test-project.outputs.test-project-path }}

      - name: Run `rw prerender`
        run: |
          yarn rw prerender --verbose
        working-directory: ${{ steps.set-up-test-project.outputs.test-project-path }}

      - name: Run `rw test web`
        run: |
          yarn rw test web --no-watch
        working-directory: ${{ steps.set-up-test-project.outputs.test-project-path }}

      - name: Run `rw test api`
        run: |
          yarn rw test api --no-watch
        working-directory: ${{ steps.set-up-test-project.outputs.test-project-path }}

      - name: Run db import tracking tests
        shell: bash
        run: |
          # Only run this for ESM projects where the vitest config file exists
          if test -f ./vitest-sort.config.ts; then
            npx vitest --config ./vitest-sort.config.ts run
          fi
        working-directory: ${{ steps.set-up-test-project.outputs.test-project-path }}/api

      - name: 🖥️ Run serve smoke tests
        working-directory: tasks/smoke-tests/serve
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: ${{ steps.set-up-test-project.outputs.test-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: 📄 Run prerender smoke tests
        working-directory: tasks/smoke-tests/prerender
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: ${{ steps.set-up-test-project.outputs.test-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: 📕 Run Storybook smoke tests
        working-directory: tasks/smoke-tests/storybook
        run: npx playwright test
        env:
          REDWOOD_TEST_PROJECT_PATH: ${{ steps.set-up-test-project.outputs.test-project-path }}
          REDWOOD_DISABLE_TELEMETRY: 1
