name: 🔭 Telemetry Check

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  telemetry-check:
    runs-on: ${{ inputs.os }}

    env:
      REDWOOD_REDIRECT_TELEMETRY: 'http://127.0.0.1:48619' # Random port

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up job
        uses: ./.github/actions/set-up-job

      - name: 📢 Listen for telemetry (CCA)
        run: node ./.github/actions/telemetry_check/check.mjs --mode cca

      - name: 📢 Listen for telemetry (CLI)
        run: node ./.github/actions/telemetry_check/check.mjs --mode cli
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
