name: Universal Deploy Tests

on:
  workflow_call:

jobs:
  ud-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up job
        uses: ./.github/actions/set-up-job

      - run: yarn vitest run
        working-directory: ./tasks/ud-tests
