// This file was generated by CedarJS
import * as Cell from './PostsCell.js'
import type { CellProps } from '@cedarjs/web'
import type { FindPosts, FindPostsVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './PostsCell.js'

type CellInputs = CellProps<SuccessType, FindPosts, typeof Cell, FindPostsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
